---
logs:
    descriptor:
        type: "console"
    options:
        level: "trace"

counters:
    descriptor:
        type: log
    options:
        timeout: 10000

persistence:
    # MongoDB persistence
    descriptor:
        group: "pip-services-dummies"
        type: "mongodb"
    connection:
        type: "mongodb"
        host: "localhost"
        database: "pipservicestest"
    options:
        server:
            poolSize: 4
            socketOptions:
                keepAlive: 1
                connectTimeoutMS: 5000
            auto_reconnect: true
        debug: false
    # # File persistence        
    # descriptor:
    #     group: "pip-services-dummies"
    #     type: "file"
    # options:
    #     file: "./data/dummies.json"        
    # # In-memory persistence        
    # descriptor:
    #     group: "pip-services-dummies"
    #     type: "memory"

controllers:
    descriptor:
        group: "pip-services-dummies"

clients:
  - descriptor:
        group: "pip-services-dummies"
        type: "lambda"
        version: "1.0"
    endpoint:
        function: "arn:aws:lambda:us-east-1:268549927901:function:pip-services-template-node"
        region: "us-east-1"
    options:
        access_key_id: "ZZZZZZ5Z4DEVJYZ2PUXA"
        secret_access_key: "ZZZZZZWjEUNWVdpPqVGjHSfwTjer//pHqBfsKkMU" 
        timeout: 30000

services:
  - descriptor:
        group: "pip-services-dummies"
        type: "seneca"
        version: "1.0"
    endpoint:
        protocol: "tcp"
        host: "localhost"
        port: 80401
  - descriptor:
        group: "pip-services-dummies"
        type: "rest"
        version: "1.0"
    endpoint:
        protocol: "http"
        host: "localhost"
        port: 80001
