---
logs:
    descriptor:
        type: "console"
    options:
        "level": 10

counters:
    descriptor:
        type: "log"
    options:
        timeout: 10000

persistence:
    # Persistence using MongoDb
    descriptor:
        group: "pip-services-dummies"
        type: "mongodb"
    connection:
        type: "mongodb"
        host: "192.168.99.100"
        port: 27017
        database: "pipservicestest"
    options:
        server:
            poolSize: 4
            socketOptions:
                keepAlive: 1
                connectTimeoutMS: 5000
            auto_reconnect: true
        debug: false
    # # Persistence using flat files
    # descriptor:
    #     group: "pip-services-dummies"
    #     type: "file"
    # options:
    #     path: "./data/dummies.json"
    # # Persistence using memory storage
    # descriptor:
    #     group: "pip-services-dummies"
    #     type: "memory"

controllers:
  - descriptor:
        group: "pip-services-dummies"

clients:
#  - descriptor:
#      group: "pip-services-dummies"
#      type: "lambda"
#      version: "1.0"
#    endpoint:
#      function: "arn:aws:lambda:us-east-1:268549927901:function:pip-services-template-node"
#      region: "us-east-1"
#    options:
#      access_key_id: "ZZZZZZ5Z4DEVJYZ2PUXA"
#      secret_access_key: "ZZZZZZWjEUNWVdpPqVGjHSfwTjer//pHqBfsKkMU"
#      timeout: 30000

services:
  - descriptor:
      group: "pip-services-dummies"
      type: "rest"
      version: "1.0"
    endpoint:
      protocol: "http"
      host: "0.0.0.0"
      port: 80001
